name: Windows

on:
  push:
    branches: [ dev, master ]
  pull_request:
    branches: [ dev, master ]
  schedule:
    - cron: "1 * * * *"

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
    - name: Test
      run: cargo test --verbose
